### ISSUE TITLE
Incorporate reference to current date in app

### ISSUE THREAD

**Issue by bjames1** [tristowww/resume-experience#1]
In order to accurately capture years of relevant experience we would have to have a current date as reference for jobs individuals may still be in. 

Process: Current date captured automatically, this date is stored, and the extracted relevant years are subtracted from this stored date.

**Comment by eristow** [comment]
On my branch, I added the current date into the prompt like so "Only consider relevant years of experience obtained from work and not from skills. For context and accurately calculating years of experience, the current is {datetime.now()}."
